CREATE DATABASE IF NOT EXISTS japcs
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE japcs;

CREATE TABLE IF NOT EXISTS usuarios (
  Id        INT AUTO_INCREMENT PRIMARY KEY,
  Nome      VARCHAR(150) NOT NULL,
  CPF       CHAR(11)     NOT NULL UNIQUE,
  Endereco  VARCHAR(200) NOT NULL,
  Bairro    VARCHAR(100) NOT NULL,
  Cidade    VARCHAR(100) NOT NULL,
  Estado    CHAR(2)      NOT NULL,
  CEP       VARCHAR(9)   NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS login (
  Id     INT AUTO_INCREMENT PRIMARY KEY,
  Login  VARCHAR(50) NOT NULL UNIQUE,
  Senha  CHAR(32)    NOT NULL,
  CPF    CHAR(11)    NOT NULL,
  CONSTRAINT fk_login_usuario
    FOREIGN KEY (CPF) REFERENCES usuarios (CPF)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS vendas (
  Id            INT AUTO_INCREMENT PRIMARY KEY,
  NumVenda      VARCHAR(20)   NOT NULL UNIQUE,
  Login         VARCHAR(50)   NOT NULL,
  NomeCompleto  VARCHAR(150)  NOT NULL,
  Produtos      TEXT          NOT NULL,
  Data          VARCHAR(19)   NOT NULL,
  Total         DECIMAL(12,2) NOT NULL,
  Pagamento     VARCHAR(30)   NOT NULL
) ENGINE=InnoDB;
